package com.raccoons.tda.api.request;

public enum ResponseType {

    CANCEL_ORDER,
    GET_ORDER,
    GET_ORDERS_BY_PATH,
    GET_ORDERS_BY_QUERY,
    PLACE_ORDER,
    REPLACE_ORDER,
    CREATE_SAVED_ORDER,
    DELETE_SAVED_ORDER,
    GET_SAVED_ORDER,
    GET_SAVED_ORDERS_BY_PATH,
    REPLACE_SAVED_ORDER,
    GET_ACCOUNT,
    GET_ACCOUNTS

}
